### ISSUE TITLE
load_texts_as_corpus NameError

### ISSUE THREAD

**Issue by dancing-with-coffee** [lovit/sejong_corpus_cleaner#4]
안녕하세요. 텍스트마이닝을 공부하는 대학원생입니다. 세종코퍼스를 사용하려고 보다가, cleaner 코드를 만들어주신걸 발견해서 git clone 하여 사용하고 있습니다.

제가 1월 31일에 clone해서 지금 사용하고 있는데, Readme.md에 쓰신거랑 다른 내용들이 몇가지 있어서 적어보려고 합니다.

(혹시, 수정중에 계시는 거라면, 무시하거나 comment를 남겨주시면 감사하겠습니다.)

1. 제시해주신 프로젝트 경로에서 from sejong_corpus_cleaner를 하면 import가 되지 않습니다.
script 폴더 기준으로 상위 폴더에 있어서, os와 sys 라이브러리를 이용해서 path를 잡아주거나, 코드를 sejong_corpus_cleaner와 같은 경로에 놓으니 잘 작동했습니다.

2. load_texts_as_eojeol_morphtags와 load_text_as_corpus 함수의 설명이 바뀐 것 같습니다.

load_texts_as_eojeol_morphtags 함수를 사용하여 결과를 출력해보니,

어절\t형태소/POS + ... 형태로 출력됩니다. 실제 내부 코드를 보니 결과는 제대로 나온 것 같습니다.

3. load_texts_as_corpus 내부에 load_colloquial_text_as_eojeol_morphtag 뒤에 's'가 하나 빠졌습니다.

_loader가 수정되어 있어서, 함수 이름도 통일하시다가 빼먹으신 것 같습니다.

이 정도가 제가 발견한 내용인데, 평소에 블로그랑 깃허브 정말 참고 많이하고 있어서 감사드리는 마음에 혹시나 도움이 될까 하여 올려봅니다.

좋은 하루 되시고, 항상 감사드립니다!

**Comment by lovit** [comment]
안녕하세요. 커멘트 남겨 주셔서 감사합니다. 저도 세종 말뭉치 코드를 어떻게 정리할지 명확히 하지 않은 상태에서 작업을 시작해서 오류가 많습니다. @Kim-Yongdam 님 덕분에 README 업데이트와 오류를 확인할 수 있었습니다.

커멘트 남겨 주신 내용들에 대한 수정 내용입니다.

1. 다른 사용자들이 햇갈리지 않도록 sys.path 에 local repository 주소를 넣으라는 부분을 readme 에 추가하였습니다.

2. 설명이 바뀌어 있었네요 (부끄럽네요). 내용을 서로 바꿔뒀습니다.

3. _loader.py 에서 load-texts_as_eojeol_morphtag  로 되어있는 부분을 수정하였습니다.

공유하는 작업물들이 참고가 된다고 하니 저도 감사드립니다. @Kim-Yongdam 님의 커멘트는 정말 도움이 되었습니다. 감사합니다!!!

**Comment by dancing-with-coffee** [comment]
> 안녕하세요. 커멘트 남겨 주셔서 감사합니다. 저도 세종 말뭉치 코드를 어떻게 정리할지 명확히 하지 않은 상태에서 작업을 시작해서 오류가 많습니다. @Kim-Yongdam 님 덕분에 README 업데이트와 오류를 확인할 수 있었습니다.
> 
> 커멘트 남겨 주신 내용들에 대한 수정 내용입니다.
> 
> 1. 다른 사용자들이 햇갈리지 않도록 sys.path 에 local repository 주소를 넣으라는 부분을 readme 에 추가하였습니다.
> 2. 설명이 바뀌어 있었네요 (부끄럽네요). 내용을 서로 바꿔뒀습니다.
> 3. _loader.py 에서 load-texts_as_eojeol_morphtag  로 되어있는 부분을 수정하였습니다.
> 
> 공유하는 작업물들이 참고가 된다고 하니 저도 감사드립니다. @Kim-Yongdam 님의 커멘트는 정말 도움이 되었습니다. 감사합니다!!!

답글 달아주셔서 정말 감사합니다! 블로그랑 github에서 정말 많은 도움 받고있습니다ㅠㅠ soynlp도 잘 사용하고 있습니다! 정말 멋지십니다. 바쁘신데 수정해주셔서 감사합니다. 저도 열심히 공부해서 도움이 될 수 있는 내용들이 있으면 정말 좋겠습니다.
