### ISSUE TITLE
오타

### ISSUE THREAD

**Issue by zidane100e** [lovit/sejong_corpus_cleaner#7]
안녕하세요
오타로 생각되어 글 남깁니다.

simplifier/_lr.py 에서
eojeol_morphtags_to_lr 함수 맨 뒤 (line 122) 부분
```python
raise ValueError('Exception: eojeol = {}, morphtag = {}'.format(eojeol, morphtag))
```
morphtag --> morphtags 아닌가요?

이  예외처리가 생긴 것이 (세종 코퍼스 아님) 뉴스에 대해 적용하면서 생긴 것인데 왜 생긴 것인지요? 

제2·제3의
--> 제/XPN 2/SN ·/SP 제/XPN 3/SN 의/JKG

**Comment by lovit** [comment]
커멘트 남겨주셔서 감사합니다. 이전 코드들에 문제점들이 많이 발견되어서 최근에 리팩토링을 하였습니다.
